# Generated by Django 4.2 on 2023-05-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0003_alter_battle_options_battle_deluxe1mc1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='minuto6VueltaMC2',
            field=models.IntegerField(default=0),
        ),
    ]
